{% set name = "dm-tree" %}
{% set version = "0.1.5" %}
{% set sha256 = "a951d2239111dfcc468071bc8ff792c7b1e3192cab5a3c94d33a8b2bda3127fa" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  ignore_run_exports:
    - libgcc-ng
    - libstdcxx-ng

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - bazel {{ bazel }}
    # Use pins to control cos6/cos7 match
    - libgcc-ng  {{ libgcc }}
    - libstdcxx-ng  {{ libstdcxx }}
  host:
    - python {{ python }}
    # Use pins to control cos6/cos7 match
    - libgcc-ng  {{ libgcc }}
    - libstdcxx-ng  {{ libstdcxx }}
  run:
    - python {{ python }}
    - six {{ six }}
    # Use pins to control cos6/cos7 match
    - libgcc-ng  {{ libgcc }}
    - libstdcxx-ng  {{ libstdcxx }}

test:
  imports:
    - tree

about:
  home: https://github.com/deepmind/tree
  license: Apache License 2.0
  license_family: Apache
  license_file: 'LICENSE'
  summary: A library for working with nested data structures.
  description: |
      Tree is a library for working with nested data structures. In a way, tree generalizes
      the builtin map function which only supports flat sequences, and allows to apply a
      function to each "leaf" preserving the overall structure.
  doc_url: https://github.com/deepmind/tree
  dev_url: https://github.com/deepmind/tree

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
