{% set name = "dm-tree" %}
{% set version = "0.1.8" %}
{% set sha256 = "0fcaabbb14e7980377439e7140bd05552739ca5e515ecb3119f234acee4b9430" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}      # [ ppc_arch != "p10"]
    - {{ compiler('cxx') }}    # [ ppc_arch != "p10"]
    - bazel {{ bazel }}
    - cmake {{ cmake }}
    - make
  host:
    - python {{ python }}
  run:
    - python {{ python }}
    - six {{ six }}

test:
  imports:
    - tree

about:
  home: https://github.com/deepmind/tree
  license: Apache License 2.0
  license_family: Apache
  license_file: 'LICENSE'
  summary: A library for working with nested data structures.
  description: |
      Tree is a library for working with nested data structures. In a way, tree generalizes
      the builtin map function which only supports flat sequences, and allows to apply a
      function to each "leaf" preserving the overall structure.
  doc_url: https://github.com/deepmind/tree
  dev_url: https://github.com/deepmind/tree

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
